### ISSUE TITLE
Proof Reading E-Mail

### ISSUE THREAD

**Issue by micky-m** [codeforbielefeld/Digitaltag2021#10]
Hier ist ein erster Entwurf als Preview zu sehen:
https://github.com/codeforbielefeld/Digitaltag2021/blob/main/preview_mail.pdf

Ist der Text so in Ordnung? Noch mehr Inhalte? 

Ich würde gerne in einem Satz noch schreiben, was Open Data ist. Hat jemand passende Formulierungen?

**Comment by grafsen** [comment]
Ist es sinnvoll noch unsere Adressen aus den sozialen Netzwerken mit hinzuzufügen? 

Als Open Data (aus englisch open data ‚offene Daten‘) werden Daten bezeichnet, die von jedermann zu jedem Zweck genutzt, weiterverbreitet und weiterverwendet werden dürfen.[1] 

1  Jörn von Lucke, Christian Geiger: Open Government Data (Frei verfügbare Daten des öffentlichen Sektors). Hrsg.: zeppelin university. Friedrichshafen 3. Dezember 2010 (zu.de [PDF]).

-> so sieht's Wikipedia und besser könnte ich es momentan (früh morgens) auch nicht ausdrücken.

Ansonsten finde ich die E-Mail sehr gelungen! Danke :)
