### ISSUE TITLE
Standorte der Stationen

### ISSUE THREAD

**Issue by schokocookie25** [codeforbielefeld/Digitaltag2021#12]

**Comment by schokocookie25** [comment]
Burg
Station1 WLAN: Sparrenburg, irgendwo wo WLAN Empfang ist
Station2 Turmhöhe: Sparrenburg Innenhof oder davor, Blick auf Turm
Hinweg
Station3 Klimmzüge:  Sportgerät Promenade
Station4 Eichen Promenade: Anfang Promenade
Station5 Bodenrichtwert: Mitte Promenade, Blick auf Musikerviertel
Station6 Durchschnittsalter: Ende Promenade Brands Busch
Rückweg
Station7 Hundewiesen: Anfang Hundewiese
Station8 Bethel: Freudenthal
Station9 Grillplätze: Ende Hundewiese

**Comment by micky-m** [comment]
Station 2 kann an der Info-Tafel zur Sparrenburg am Parkplatz zwischen Behindertenparkplatz und Fußweg runter nach Bethel angebracht werden. Da kann auch noch nachgelesen werden, das ist aus meiner Sicht schöner als im Innenhof der Burg/direkt Burggelände.
Station 4 hatte ich hinter der Sportstation gesetzt, da dort auch auf der linken Seiten von der Burg kommend eine Tafel mit allen Spendern aufgeführt ist, an der man das Ergebnis abzählen könnte. Es ist die gleiche Tafel wie auch am Anfang der Promenade. 
Das Freudenthal ist das Ende der Hundewiese, danach führt der Weg nur noch hinter Schrebergärten entlang, daher fände ich es gut, wenn dort noch auf Höhe der Wiese die Frage zu den Grillplätzen angebracht wird?!

**Comment by schokocookie25** [comment]
Ok, dann können 3 und 4 so bleiben.
Ich hatte gedacht, wir bringen die Bethel Frage Richtung Freudenthal an, da Bethel dort anfängt, und die Grillplatzfrage irgendwo im Bereich der Hundewiesen, damit da auch noch eine Station ist. Daher wollte ich 8 und 9 tauschen

**Comment by micky-m** [comment]
Ahh... dann hatte ich das falsch verstanden mit dem Tauschen von Frage 8 und 9. Das finde ich gut, dass dann die Frage zur Grillwiese noch im Bereich der Hundewiese liegt. Sorry, mein Fehler!!

**Comment by micky-m** [comment]
Tauschen erledigt.
