### ISSUE TITLE
Fragen für Variante 1b für die einzelnen Stationen

### ISSUE THREAD

**Issue by micky-m** [codeforbielefeld/Digitaltag2021#3]
Für die einzelnen Stationen fehlen noch Fragen und Antworten. In dem Mini-Beispiel haben wir aktuell zwei Fragen:

**Wie hoch ist der Turm der Sparrenburg?**
1) 15m
2) 37m
3) 97m
4) 180m

_Feedback for richtige Antworten_
Der 37 Meter hohe Turm der Sparrenburg, die auf dem 180 Meter hohen Sparrenberg liegt, bietet einen tollen Blick über die Stadt und den Teutoburger Wald. 

_Feedback für falsche Antworten_
Leider falsch! Der Turm der Sparrenburg ist 37 Meter hoch und bietet damit einen tollen Blick über die Stadt und den Teutoburger Wald. 

**Wie viele Traubeneichen wurden 2020 entlang der Promenade neu gepflanzt?**

1) 25
2) 90
3) 103
4) 190

_Feedback for richtige Antworten_
Im Januar und Herbst 2019 wurden 103 neue Traubeneichen entlang der Promenade gepflanzt. Dies war notwendig, nachdem 2018 ein großer Teil der Eschen gefällt werden mussten. Zu Beginn wurden nur 90 neue Bäume geplant - aber viel mehr Bielefelder Bürger:innen wollten mit einer Spende die Neuanpflanzungen unterstützen, so dass am Ende die Pflanzung von 103 Eichen ermöglicht worden ist. Stelen an der Promenade erinnern und danken für dieses Engagement. 

_Feedback für falsche Antworten_
Leider falsch! Im Januar und Herbst 2019 wurden 103 neue Traubeneichen entlang der Promenade gepflanzt. Dies war notwendig, nachdem 2018 ein großer Teil der Eschen gefällt werden mussten. Zu Beginn wurden nur 90 neue Bäume geplant - aber viel mehr Bielefelder Bürger:innen wollten mit einer Spende die Neuanpflanzungen unterstützen, so dass am Ende die Pflanzung von 103 Eichen ermöglicht worden ist. Stelen an der Promenade erinnern und danken für dieses Engagement.

**Comment by micky-m** [comment]
Hinten bei Brands Busch könnten die Frage gestellt werden: an wie vielen Bänken seid ihr vorbeigelaufen?

**Comment by micky-m** [comment]
Bei den Sportgeräten (gegenüber der schönen Aussicht) kann eine sportliche Aufgabe gestellt werden (Kudos an Marlena für die Frage!)

**Comment by schokocookie25** [comment]
Karte mit Hundewiesen und Wanderwegen:
https://stadtplan.bielefeld.de/app/freizeit_online/#?sidebar=overlay&sidebarStatus=open&map=10,468379.19534,5761984.00289,EPSG:25832&layers=grillplaetze_p,stadtplan_bi_gruen,hundeauslaufbereiche_pl,wandertouren_wms

**Comment by schokocookie25** [comment]
Radwegschild: Karte mit Radwegen hinterlegt
Wanderwegschild: Karte mit Wanderwegen hinterlegt
Frage dazu: Welche Farbe haben die Rad-/Wanderwege in der Karte

Sportaufgabe am Sportgerät Schöne Aussicht oder Spielplatz Freudental

**Comment by grafsen** [comment]
An einer Wiese oder an einem schönen Ausblick oder aber am Ende der Tour könnten wir folgende Frage stellen?
"Na? Nun hast du es bald geschafft! Da hättest du dir einen schönen Grillabend verdient. Das kannst du auch auf öffentlichen Grillplätzen in Bielefeld machen. Aber bitte den Müll wieder mitnehmen - danke :)"

Wie viele öffentliche Grillplätze gibt es in Bielefeld?

1.) keine
2.) 7
3.) 11
4.) 24

Richtige Antwort auf https://open-data.bielefeld.de/dataset/grillplätze zu finden --> 11 Stk.

POSITION: EGAL

**Comment by grafsen** [comment]
Am Anfang der Tour könnte man fragen oder auch irgendwo sonst - vielleicht am Ende in Verbindung zu den WLAN-Access-Points am Adenauer-Platz oder an der Musik- und Kunstschule in Bethel: 

"Dein Datenvolumen ist bald aufgebraucht. Dann logge dich doch ins WLAN "BI-FREE" ein."

Wo stehen die nächsten Access-Points für dich (Ausgangspunkt Sparrenburg)? 

1.) Adenauerplatz und Musik-/Kunstschule in Bethel
2.) Landgericht und Gilead 1 in Bethel
3.) Sparrenburg Besucherzentrum und Dr. Oetker Welt
4.) Rathaus und Kunsthalle

Richtige Antwort auf https://stadtplan.bielefeld.de/app/freizeit_online/#?sidebar=overlay&sidebarStatus=closed&map=13,467488.18367,5762707.04001,EPSG:25832&layers=wlan_bi_free_p,stadtplan_bi_gruen -> 1.) Adenauerplatz und Musik-/Kunstschule in Bethel

POSITION: NÄHE SPARRENBURG

**Comment by grafsen** [comment]
Das Musikerviertel, welches zwischen der Promenade und der Demolder Straße liegt, ist unter Bielefelder*innen bekannt für seine schönen Häuser und den verbundenen hohen Kosten für die Immobilien.

Was ist der gegenwärtige Bodenrichtwert im Musikerviertel?

1.) 550€ / qm
2.) 600€ / qm
3.) 650€ / qm 
4.) 700€ / qm

Richtige Antwort auf https://www.boris.nrw.de/borisplus/?lang=de zu finden --> 650€/qm. 

BORIS-NRW ist das zentrale Informationssystem der Gutachterausschüsse und des Oberen Gutachterausschusses für Grundstückswerte über den Immobilienmarkt in Nordrhein-Westfalen. Hier kannst an anhand einer digitalen Karte die aktuellen Bodenrichtwerte (d)eines Grundstücks (Preis pro Quadratmeter) ermitteln.

POSITION: EGAL (Frage sollte aber in Richtung Musikerviertel hängen)

**Comment by schokocookie25** [comment]
Auf deinem Weg bis zu dieser Station bist du sicherlich schon einigen Menschen unterschiedlichen Alters begegnet. 
In welchem Bielefelder Stadtteil ist das Durchschnittsalter am niedrigsten?
1.) Mitte
2.) Gadderbaum
3.) Schildesche
4.) Brackwede

Den Hinweis zur richtigen Antwort findest du im Open Data Portal der Stadt Bielefeld:
https://stadtplan.bielefeld.de/app/statistik/#?sidebar=legend&sidebarStatus=open&map=7,468152.5616,5764386.17546,EPSG:25832&layers=stadtplan_bi,stadtbez_durchschnittsalter_pl

Richtige Antwort:
1.) Mitte
Mit einem Durchschnittsalter von 40.8 Jahren wohnen in Bielefeld Mitte im Schnitt die jüngsten Menschen in Bielefeld. Darauf folgt Heepen mit 42.8. Am Ältesten sind die Menschen in Dornberg mit durchschnittlich 45 Jahren.

**Comment by schokocookie25** [comment]
Frage zu den Hundewiesen:
Position: Hundewiese:

Wie viele Hundeauslaufbereiche gibt es in ganz Bielefeld
1.) 3
2.) 30
3.) 22
4.) 12

Den Hinweis zur richtigen Antwort findest du im Open Data Portal der Stadt Bielefeld:
https://stadtplan.bielefeld.de/app/freizeit_online/#?sidebar=legend&sidebarStatus=open&map=8,468379.19534,5761984.00289,EPSG:25832&layers=hundeauslaufbereiche_pl,wandertouren_wms,stadtplan_bi_gruen

Richtige Antwort:
1.) 12

**Comment by schokocookie25** [comment]
Frage zum Fitnessgerät:
Position: Fitnessgerät Schöne Aussicht

Teste die verschiedenen Stationen des Sportgerätes doch einmal aus. Welche Übung gefällt dir am besten? Wie viele Klimmzüge schaffst du? 

Apropos Klimmzüge: Wie viele Klimmzüge sind der amtierende Weltrekord?
1.) 36
2.) 202
3.) 612
4.) 1045

Richtige Antwort: 3.) 612
Den Klimmzug Weltrekord mit den meisten aufeinanderfolgenden Klimmzügen hält Lee Chin-Yong aus Korea. Er schaffte 612 Klimmzüge im Jahr 1994 im Alter von 70 Jahren! Er braucht dafür 2 Stunden und 40 Minuten!

**Comment by micky-m** [comment]
Auf der anderen Seite der Hundewiese beginnt der Bielefelder Stadtteil Bethel. Seit über 150 Jahren wirkt die namensgebende v. Bodelschwinghsche Stiftung Bethel in diesem Stadtteil und weit darüber hinaus, um umzusetzen, dass alle Menschen in ihrer Verschiedenheit selbstverständlich zusammen leben, lernen und arbeiten können. Das Bethel College in Kansas, USA teilt auch neben dem Namen Bethel den Ansatz gelebter Diversität in der Gemeinschaft. Die Bibliothek des Bethel Colleges hat sich dem Thema Open Access gewidmet und unterstützt dieses Konzept.

Häufig gehen die Begriffe Open Access, Open Data und Open Science ineinander über. Unterstützt auch die Universität Bielefeld diese Konzepte?

1) Ja
2) Nein

Richtige Antwort ist JA: (Antwort wird noch formuliert)
https://www.ub.uni-bielefeld.de/ub/digital/oa/
Mitarbeit der Uni Bielefeld an den folgenden Projekten:
https://open-access.net/
https://ask-open-science.org

**Comment by micky-m** [comment]
9 Fragen in Gdrive angelegt - siehe QR Codes
